### ISSUE TITLE
Adding multiple master nodes in same page

### ISSUE THREAD

**Issue by praveenmj34** [sselvamani22/jOrgChart#1]
Thanks for giving a wonderful org chart component. I am newbie to jquery and I need help that how can i create multiples master nodes in same page. Like i have to create another Org chart with Andrey only. So if i have to create multiple org chart in same page. How can i create.

**Comment by praveenmj34** [comment]
Thanks for giving a wonderful org chart component. I am newbie to jquery and I need help that how  can i create multiples master nodes in same page.

**Comment by selvamani-subramani** [comment]
I hope you go-though the code flow. This orgchart was build with multiple support
master nodes. You can create multiple master nodes by using input
json format. You can `fork` and edit the input json. The json have parent_id, if it is empty then it will
act as master node. I hope you enjoy with my orgchat. If you found any
issues or need any enhancement please add a pull-request or rise an issue.
If you really like this project please give a star.

**Comment by praveenmj34** [comment]
After creating another master node. If i add another child then the child node is attached to previous master node. The functionality is working on existing master node. If i create a new master node i am not able to create the child nodes under it.
