### ISSUE TITLE
Not able to delete the created node using Add node button

### ISSUE THREAD

**Issue by praveenmj34** [sselvamani22/jOrgChart#2]
I have created new org nodes in my browser using "Add Node" window. But i am not able to delete the created node. Getting the below error in developer tool: SCRIPT5007: Unable to get value of the property 'split': object is null or undefined

**Comment by selvamani-subramani** [comment]
Thanks. I have made some change.

**Comment by selvamani-subramani** [comment]
Hi, 

Now I fixed the issue which you said. So I am closing the issue.
