### ISSUE TITLE
Slow response time when adding nodes

### ISSUE THREAD

**Issue by Ethrios** [sselvamani22/jOrgChart#3]
Hello!   I think i found a little issue on the example you provided.  When trying to add nodes, the "load" time for the popup screen keeps increasing 2x 

Try adding a lot of nodes (using the add node button), you'll notice how it takes longer and longer to load up.

**Comment by sselvamani22** [comment]
Hi Ethrois,
Thanks for pointing out the issues. Have fixed now.
