### ISSUE TITLE
Loading nodes on expand button click event

### ISSUE THREAD

**Issue by gomsmaasi** [sselvamani22/jOrgChart#4]
My Org chart data is more than 25k. i would like to implement loading nodes on '.exp-col' click event...
is it possible to append the tree node inside existing orgchart insted of creating new chart...

Any idea....

**Comment by selvamani-subramani** [comment]
Yeah. Actually the tree is building from un-order list(ul&li). First you form the list and append to the main list. Then call the plugin function. It will build the tree.

**Comment by gomsmaasi** [comment]
Yes... once i append the 2nd level node list with 1st level and when i call the plugin function it creates node from the beginning as a new chart.. it results 2 org chart... one orgchart is until 1st level, another orgchart is untill 2nd level. we can remove the first orgchart and loads another. i dont want to load from the beginning. so the plugin loads the node from the parent not from the selected nodes... how to do so....

**Comment by selvamani-subramani** [comment]
This plugin doesn't support to refresh a single node. Once you have framed `ul` list, then call plugin. When you call plugin it will destroy the orgchart which currently displaying on UI and take a input from `ul` and build new orgchart.

**Comment by gomsmaasi** [comment]
Hoo no.......

**Comment by selvamani-subramani** [comment]
Hi gomsmaasi,
Now this design pattern has been improved. Now the org charts creating and updating node will be fast. Please try it on you end and let me know if you have any problem. If any things go wrong, we will restructure it.
